language: go

go:
  - 1.11.x

env:
  global:
    - GO111MODULE=on

script:
  - GOOS=linux go build
  - GOOS=darwin go build
  - GOOS=freebsd go build
  - GOOS=windows go build

  - go test -v -coverprofile=coverage.txt -covermode=atomic
  - go test -v -race

after_success:
  - bash <(curl -s https://codecov.io/bash)