language: go

go:
  - 1.11.x
  - 1.12.x

env:
  global:
    - GO111MODULE=on
  matrix:
    - SUITE=build
    - SUITE=test
    - SUITE=codecov

matrix:
  exclude:
    - go: 1.11.x
      env: SUITE=codecov

script:
  - ./run-travisci.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)